function params = loadparams()
%LOADPARAMS Summary of this function goes here
%   Detailed explanation goes here

params.windowSize = 256;
params.overlapLength = 128;
params.fs = 44100;
params.valProportion = 1/5;

params.afe = audioFeatureExtractor('SampleRate',params.fs, ...
    'Window',hann(params.windowSize,"Periodic"), ...
    'OverlapLength',params.overlapLength, ...
    ...
    'spectralCentroid',true, ...
    'spectralCrest',true, ...
    'spectralEntropy',true, ...
    'spectralFlux',true, ...
    'spectralKurtosis',true, ...
    'spectralRolloffPoint',true, ...
    'spectralSkewness',true, ...
    'spectralSlope',true, ...
    'harmonicRatio',true);
  


end

